security:
    providers:
        db_provider:
            entity:
                class: AppBundle:User
                property: username
    
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost:      8

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            pattern: ^/
            anonymous: ~
            provider: db_provider
            form_login:
                login_path: /session/login
                check_path: /session/login_check
                username_parameter: email
                password_parameter: password
                failure_handler: app.security.authentication_handler
                success_handler: app.security.authentication_handler
            logout:
                path:   /session/logout
                success_handler: app.security.authentication_handler
                invalidate_session:   true